"""
Export Utilities
=================
PDF, HTML, Markdown, CSV, and PNG/SVG export for all modules.
Uses Python stdlib + optional reportlab/weasyprint for PDF.
"""

from __future__ import annotations

import csv
import io
import json
import logging
import os
import tempfile
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List, Optional, Union

logger = logging.getLogger(__name__)


# ── HTML export ──────────────────────────────────────────────

def export_html(
    content: str,
    title: str = "Biomaterials Hackathon Analyser — Export",
    output_path: Optional[str] = None,
    css: str = "",
) -> str:
    """Export content as a standalone HTML file.

    Parameters
    ----------
    content : str
        HTML body content (can include tables, headings, etc.).
    title : str
        HTML page title.
    output_path : str, optional
        File path to write. If None, returns HTML string.
    css : str
        Additional CSS to inject.

    Returns
    -------
    str
        Full HTML string (also written to output_path if provided).
    """
    default_css = """
    body {
        font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
        max-width: 1100px;
        margin: 0 auto;
        padding: 20px;
        color: #333;
        line-height: 1.6;
    }
    h1, h2, h3, h4 { color: #1a237e; }
    table {
        border-collapse: collapse;
        width: 100%;
        margin: 12px 0;
    }
    th, td {
        border: 1px solid #ddd;
        padding: 8px 12px;
        text-align: left;
    }
    th { background: #f5f5f5; font-weight: 600; }
    tr:nth-child(even) { background: #fafafa; }
    .warning {
        background: #fff3cd;
        border: 1px solid #ffc107;
        padding: 12px;
        border-radius: 4px;
        margin: 8px 0;
    }
    .success {
        background: #d4edda;
        border: 1px solid #28a745;
        padding: 12px;
        border-radius: 4px;
        margin: 8px 0;
    }
    .footer {
        margin-top: 30px;
        padding-top: 10px;
        border-top: 1px solid #ddd;
        font-size: 0.85em;
        color: #999;
    }
    """

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{title}</title>
    <style>{default_css}\n{css}</style>
</head>
<body>
    <h1>{title}</h1>
    {content}
    <div class="footer">
        Generated by Biomaterials Hackathon Analyser on {datetime.now().strftime('%Y-%m-%d %H:%M')}
    </div>
</body>
</html>"""

    if output_path:
        Path(output_path).parent.mkdir(parents=True, exist_ok=True)
        with open(output_path, "w", encoding="utf-8") as f:
            f.write(html)
        logger.info("HTML exported to %s", output_path)

    return html


# ── Markdown export ──────────────────────────────────────────

def export_markdown(
    sections: List[Dict[str, str]],
    title: str = "Biomaterials Report",
    output_path: Optional[str] = None,
) -> str:
    """Export content as Markdown.

    Parameters
    ----------
    sections : list of dict
        Each dict has 'heading' and 'content' keys.
    title : str
        Document title (H1).
    output_path : str, optional
        File path to write.

    Returns
    -------
    str
        Markdown string.
    """
    lines = [f"# {title}\n"]
    lines.append(f"*Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}*\n")

    for section in sections:
        heading = section.get("heading", "Section")
        content = section.get("content", "")
        level = section.get("level", 2)
        prefix = "#" * level
        lines.append(f"\n{prefix} {heading}\n")
        lines.append(content)

    md = "\n".join(lines)

    if output_path:
        Path(output_path).parent.mkdir(parents=True, exist_ok=True)
        with open(output_path, "w", encoding="utf-8") as f:
            f.write(md)
        logger.info("Markdown exported to %s", output_path)

    return md


# ── CSV export ───────────────────────────────────────────────

def export_csv(
    headers: List[str],
    rows: List[List[Any]],
    output_path: Optional[str] = None,
) -> str:
    """Export tabular data as CSV.

    Parameters
    ----------
    headers : list of str
        Column headers.
    rows : list of list
        Data rows.
    output_path : str, optional
        File path to write.

    Returns
    -------
    str
        CSV string.
    """
    buf = io.StringIO()
    writer = csv.writer(buf)
    writer.writerow(headers)
    writer.writerows(rows)
    csv_str = buf.getvalue()

    if output_path:
        Path(output_path).parent.mkdir(parents=True, exist_ok=True)
        with open(output_path, "w", encoding="utf-8", newline="") as f:
            f.write(csv_str)
        logger.info("CSV exported to %s", output_path)

    return csv_str


# ── JSON export ──────────────────────────────────────────────

def export_json(
    data: Any,
    output_path: Optional[str] = None,
    indent: int = 2,
) -> str:
    """Export data as JSON.

    Parameters
    ----------
    data : any
        JSON-serialisable data.
    output_path : str, optional
        File path to write.

    Returns
    -------
    str
        JSON string.
    """
    json_str = json.dumps(data, indent=indent, default=str, ensure_ascii=False)

    if output_path:
        Path(output_path).parent.mkdir(parents=True, exist_ok=True)
        with open(output_path, "w", encoding="utf-8") as f:
            f.write(json_str)
        logger.info("JSON exported to %s", output_path)

    return json_str


# ── PNG/SVG export (matplotlib figures) ──────────────────────

def export_figure(
    fig,
    output_path: str,
    dpi: int = 150,
    fmt: str = "png",
) -> str:
    """Export a matplotlib Figure to PNG or SVG.

    Parameters
    ----------
    fig : matplotlib.figure.Figure
        The figure to export.
    output_path : str
        File path to write.
    dpi : int
        Resolution (for raster formats).
    fmt : str
        Format: "png", "svg", "pdf".

    Returns
    -------
    str
        Output file path.
    """
    Path(output_path).parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(output_path, dpi=dpi, format=fmt, bbox_inches="tight")
    logger.info("Figure exported to %s", output_path)
    return output_path


# ── Table to HTML ────────────────────────────────────────────

def table_to_html(
    headers: List[str],
    rows: List[List[Any]],
    highlight_column: Optional[int] = None,
) -> str:
    """Convert tabular data to an HTML table string.

    Parameters
    ----------
    headers : list of str
        Column headers.
    rows : list of list
        Data rows.
    highlight_column : int, optional
        Column index to bold.

    Returns
    -------
    str
        HTML table string.
    """
    html = "<table>\n<thead><tr>"
    for h in headers:
        html += f"<th>{h}</th>"
    html += "</tr></thead>\n<tbody>\n"

    for row in rows:
        html += "<tr>"
        for i, cell in enumerate(row):
            val = str(cell) if cell is not None else ""
            if highlight_column is not None and i == highlight_column:
                html += f"<td><b>{val}</b></td>"
            else:
                html += f"<td>{val}</td>"
        html += "</tr>\n"

    html += "</tbody></table>"
    return html


# ── PDF export (via HTML) ────────────────────────────────────

def export_pdf(
    content: str,
    title: str = "Biomaterials Report",
    output_path: Optional[str] = None,
) -> Optional[str]:
    """Export HTML content to PDF using weasyprint or fpdf2.

    Falls back gracefully if neither is available.

    Parameters
    ----------
    content : str
        HTML body content.
    title : str
        Document title.
    output_path : str, optional
        File path. Auto-generated if None.

    Returns
    -------
    str or None
        Output path, or None if PDF generation unavailable.
    """
    if output_path is None:
        output_path = os.path.join(
            tempfile.gettempdir(),
            f"biomaterials_report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf",
        )

    html = export_html(content, title=title)

    # Try weasyprint first
    try:
        import weasyprint
        weasyprint.HTML(string=html).write_pdf(output_path)
        logger.info("PDF exported via weasyprint to %s", output_path)
        return output_path
    except ImportError:
        pass

    # Try fpdf2 as fallback (simpler, no system deps)
    try:
        from fpdf import FPDF

        pdf = FPDF()
        pdf.add_page()
        pdf.set_auto_page_break(auto=True, margin=15)
        pdf.set_font("Helvetica", size=10)

        # Simple text rendering (strips HTML)
        import re
        text = re.sub(r"<[^>]+>", "", content)
        text = text.replace("&amp;", "&").replace("&lt;", "<").replace("&gt;", ">")

        pdf.set_font("Helvetica", "B", 16)
        pdf.cell(0, 10, title, new_x="LMARGIN", new_y="NEXT")
        pdf.set_font("Helvetica", size=10)
        pdf.ln(5)

        for line in text.split("\n"):
            line = line.strip()
            if line:
                pdf.multi_cell(0, 5, line)
                pdf.ln(2)

        pdf.output(output_path)
        logger.info("PDF exported via fpdf2 to %s", output_path)
        return output_path
    except ImportError:
        pass

    logger.warning("PDF export unavailable (install weasyprint or fpdf2)")
    return None


# ── Briefing export helper ───────────────────────────────────

def export_briefing(
    briefing_html: str,
    project_name: str = "Biomaterials Project",
    output_dir: Optional[str] = None,
) -> Dict[str, str]:
    """Export a briefing in multiple formats.

    Parameters
    ----------
    briefing_html : str
        HTML content of the briefing.
    project_name : str
        Project name for file naming.
    output_dir : str, optional
        Output directory. Defaults to temp directory.

    Returns
    -------
    dict
        Mapping of format -> file path for successfully exported files.
    """
    if output_dir is None:
        output_dir = tempfile.mkdtemp(prefix="biomaterials_briefing_")

    safe_name = "".join(c for c in project_name if c.isalnum() or c in " _-").strip()
    safe_name = safe_name.replace(" ", "_")
    timestamp = datetime.now().strftime("%Y%m%d_%H%M")

    exports = {}

    # HTML
    html_path = os.path.join(output_dir, f"{safe_name}_{timestamp}.html")
    export_html(briefing_html, title=project_name, output_path=html_path)
    exports["html"] = html_path

    # PDF
    pdf_path = os.path.join(output_dir, f"{safe_name}_{timestamp}.pdf")
    result = export_pdf(briefing_html, title=project_name, output_path=pdf_path)
    if result:
        exports["pdf"] = pdf_path

    return exports
